apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-harveymoj-nodejs App
name: labs-harveymoj-nodejs
home: https://github.com/hmcts/labs-harveymoj-nodejs
version: 0.0.8
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'https://hmctsprod.azurecr.io/helm/v1/repo/'
